#!/usr/bin/env php
<?php

use yii\console\Application;

define ('DS', DIRECTORY_SEPARATOR);
define('FILE_PATH_ROOT', __DIR__ . DS);
define('FILE_PATH_ROOT_WEB', FILE_PATH_ROOT . 'web' . DS);
define('FILE_PATH_VENDOR', FILE_PATH_ROOT . 'vendor' . DS);

defined('YII_ENV') or define('YII_ENV', file_exists(FILE_PATH_ROOT . '.prod') ? 'prod' : 'dev');
defined('YII_DEBUG') or define('YII_DEBUG', YII_ENV === 'dev');

define('FILE_PATH_CONFIG', FILE_PATH_ROOT . 'config' . DS);
define('FILE_PATH_CONFIG_ENV', FILE_PATH_CONFIG . YII_ENV . DS);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(FILE_PATH_VENDOR . 'autoload.php');
require(FILE_PATH_VENDOR . 'yiisoft' . DS . 'yii2' . DS . 'Yii.php');

$aConfig = require(FILE_PATH_CONFIG_ENV . 'main_console.php');

$oApplication = new Application($aConfig);
$sExitCode = $oApplication->run();

exit($sExitCode);