<?php

return array(
    'application.components._extend.*',
    'application.components.*',
    'application.components.loader.*',
    'application.components.call.*',
    'application.components.object.*',
    //
    'application.components.price.*',
    'application.components.price._extend.*',
    //
    'application.call._extend.*',
    'application.call.*',
    'application.call.account.*',
    'application.call.character.*',
    'application.call.eve.*',
    //
    'application.widgets._extend.*',
    'application.widgets.*',
    //
    'application.models._extend.*',
    'application.models.*',
    'application.models_api.account.*',
    'application.models_api.character.*',
    'application.models_api.common.*',
    'application.models_api.corporation.*',
    'application.models_dump.*',
    //
    'application.forms._extend.*',
    'application.forms.*',
    //
    'application.controllers._extend.*',
    'application.controllers.*',
    //
    'application.controllers.user._extend.*',
    'application.controllers.user.*',
);