<?php

namespace app\models\dump;

use app\models\extend\AbstractActiveRecord;

/**
 * Class IndustryActivityProducts
 *
 * @package app\models\dump
 *
 * @property int      $typeID
 * @property int      $activityID
 * @property int      $productTypeID
 * @property int      $quantity
 *
 *
 * @property InvTypes $invType
 * @property InvTypes $productType
 */
class IndustryActivityProducts extends AbstractActiveRecord
{
    public static function tableName()
    {
        return 'industryActivityProducts';
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function getInvType()
    {
        return $this->hasOne(InvTypes::class, ['typeID' => 'typeID']);
    }

    public function getProductType()
    {
        return $this->hasOne(InvTypes::class, ['typeID' => 'productTypeID']);
    }
}