<?php

namespace app\models\dump;

use app\models\extend\AbstractActiveRecord;

/**
 * Class IndustryActivityMaterials
 *
 * @package app\models\dump
 *
 * @property int      $typeID
 * @property int      $activityID
 * @property int      $materialTypeID
 * @property int      $quantity
 *
 *
 * @property InvTypes $invType
 * @property InvTypes $materialInvType
 */
class IndustryActivityMaterials extends AbstractActiveRecord
{
    public static function tableName()
    {
        return 'industryActivityMaterials';
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function getInvType()
    {
        return $this->hasOne(InvTypes::class, ['typeID' => 'typeID']);
    }

    public function getMaterialType()
    {
        return $this->hasOne(InvTypes::class, ['typeID' => 'materialTypeID']);
    }
}